u

diff --git a/.github/workflows/json-diff-workflow.yml b/.github/workflows/json-diff-workflow.yml
--- a/.github/workflows/json-diff-workflow.yml
+++ b/.github/workflows/json-diff-workflow.yml
@@ -60,11 +60,9 @@ jobs:
         run: |
           file_paths=$(echo '${{ inputs.file_paths }}' | jq -r '.[]')
           for file in $file_paths; do
-            # Construct filenames for old and new JSON files
             old_json="${file}_old.json"
             new_json="${file}_new.json"
       
-            # Display file contents for debugging
             echo "Verifying contents of ${old_json}:"
             cat "${old_json}"
             echo "Verifying contents of ${new_json}:"
@@ -73,16 +71,28 @@ jobs:
             # Check if both JSON files exist and are not empty
             if [ -s "${old_json}" ] && [ -s "${new_json}" ]; then
                 # Compare OLDJSON and NEWJSON using JD
-                jd --set "${old_json}" "${new_json}" > "${file}_diff.json"
-                echo "Differences Detected in $file:"
-                cat "${file}_diff.json"
-                
-                # Extract only additions (new blocks)
-                additions=$(jd --set "${old_json}" "${new_json}" | grep '^+' | sed -e 's/^+ //')
-                echo "Additions in $file:"
-                echo "$additions"
+                jd_command_output=$(jd --set "${old_json}" "${new_json}" 2>&1)
+                echo "JD Command Output:"
+                echo "${jd_command_output}"
+      
+                # Capture the exit code of JD command
+                jd_exit_code=$?
+                echo "JD Command Exit Code: ${jd_exit_code}"
+      
+                if [ ${jd_exit_code} -eq 0 ]; then
+                    echo "Differences Detected in $file:"
+                    echo "${jd_command_output}"
+                    
+                    # Extract only additions (new blocks)
+                    additions=$(echo "${jd_command_output}" | grep '^+' | sed -e 's/^+ //')
+                    echo "Additions in $file:"
+                    echo "$additions"
+                else
+                    echo "JD failed to process files. Review output above for errors."
+                fi
             else
                 echo "One or both JSON files are empty or missing for ${file}"
             fi
           done
+        
          
